title: SUPMAP.org Find great places to SUP in OR and WA
description: > # this means to ignore newlines until "baseurl:"
  SUPMAP.org || Find great places to SUP in OR and WA. Whether you're a 
  seasoned SUP enthusiast or just learning how to paddleboard, there's a place for 
  you.
permalink: ':title/'
# baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://supmap.org" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: SUPmap.org # add your name
author-img: logo.png # add your photo
about-author: # add description
social-twitter: geografa # add your Twitter handle
social-facebook: rafa-gutierrez # add your Facebook handle
social-github: geografa # add your Github handle
social-linkedin: geografa # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
